xcodeproj 'ios/Grapevine.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => 'node_modules/react-native'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'react-native-fbsdkcore', :path => 'node_modules/react-native-fbsdkcore'
pod 'react-native-fbsdklogin', :path => 'node_modules/react-native-fbsdklogin'
